mklink /D build chromium\src\build
mklink /D testing chromium\src\testing
mklink /D net chromium\src\net
mklink /D base chromium\src\base
mklink /D buildtools chromium\src\buildtools
mklink /D third_party\expat ..\chromium\src\third_party\expat
mklink /D third_party\libsrtp ..\chromium\src\third_party\libsrtp
mklink /D third_party\usrsctp ..\chromium\src\third_party\usrsctp
mklink /D third_party\libyuv ..\chromium\src\third_party\libyuv
mklink /D third_party\jsoncpp ..\chromium\src\third_party\jsoncpp
mklink /D third_party\libvpx ..\chromium\src\third_party\libvpx
mklink /D third_party\openmax_dl ..\chromium\src\third_party\openmax_dl
mklink /D third_party\boringssl ..\chromium\src\third_party\boringssl
mklink /D third_party\yasm ..\chromium\src\third_party\yasm
mklink /D third_party\libjpeg_turbo ..\chromium\src\third_party\libjpeg_turbo
mklink /D third_party\opus ..\chromium\src\third_party\opus
mklink /D third_party\protobuf ..\chromium\src\third_party\protobuf
mklink /D tools\protoc_wrapper ..\chromium\src\tools\protoc_wrapper
mklink /D tools\gyp ..\chromium\src\tools\gyp